package com.dme.automation.pages;

import com.dme.automation.base.BasePage;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.AriaRole;

public class PatientPage extends BasePage {

    public PatientPage(Page page) {
        super(page);
    }

    // =========================================================
    // Step 1: Open Sidebar
    // =========================================================
    public void openSidebar() {

        // Locator generated by Playwright Codegen
        Locator menuButton = page.locator(".bi").first();

        menuButton.waitFor();

        menuButton.click();
    }


    // =========================================================
    // Step 2: Open Patient Menu
    // =========================================================
    public void openPatientMenu() {

        Locator patientMenu = page.locator(
            "a.nav-link[data-bs-target='#menuCode-00002']"
        );

        patientMenu.waitFor();

        // Application has viewport/click issue,
        // so dispatchEvent is used.
        patientMenu.dispatchEvent("click");

        // Wait for Patient submenu
        page.locator("#menuCode-00002").waitFor();
    }


    // =========================================================
    // Step 3: Open Patients
    // =========================================================
    public void openPatients() {

        Locator patientsLink = page.locator(
            "a[href='/patientsearch']"
        );

        patientsLink.waitFor();

        // Application has viewport/click issue,
        // so JavaScript click is used.
        patientsLink.evaluate(
            "element => element.click()"
        );

        // Wait for Patients Search page
        page.waitForURL("**/patientsearch");
    }


    // =========================================================
    // Step 4: Enter Patient ID
    // =========================================================
    public void enterPatientId(String patientId) {

        Locator patientIdField = page.locator("#depositID");

        patientIdField.waitFor();

        patientIdField.fill(patientId);

        System.out.println(
            "Patient ID entered: " + patientId
        );
    }


    // =========================================================
    // Step 5: Click Search
    // =========================================================
    public void clickSearch() {

        /*
         * There are multiple links containing "Search"
         * on the page.
         *
         * Therefore, use the href/class of the actual
         * Patient Search button.
         */
        Locator searchButton = page.locator(
            "a[href='/patientsearch'].btn-primary"
        ).filter(
            new Locator.FilterOptions()
                .setHasText("Search")
        );

        searchButton.waitFor();

        /*
         * The application may report the button as
         * outside the viewport.
         *
         * JavaScript click avoids that issue.
         */
        searchButton.evaluate(
            "element => element.click()"
        );

        System.out.println(
            "Search button clicked"
        );
    }


    // =========================================================
    // Step 6: Search Patient
    // =========================================================
    public void searchPatient(String patientId) {

        // Enter Patient ID
        enterPatientId(patientId);

        // Give the application a moment to process
        // the entered value.
        page.waitForTimeout(1000);

        // Debug information
        System.out.println(
            "Patient ID value in field: "
            + page.locator("#depositID").inputValue()
        );

        // Check if browser HTML validation has any
        // invalid required fields.
        System.out.println(
            "Number of invalid fields: "
            + page.locator(":invalid").count()
        );

        // Click Search
        clickSearch();

        // Wait for search results to load
        page.waitForTimeout(3000);
    }


    // =========================================================
    // Step 7: Click Patient ID and Open Patient Details
    // =========================================================
    public Page openPatient(String patientId) {

        System.out.println(
            "Clicking Patient ID: " + patientId
        );

        /*
         * Clicking the Patient ID opens a new browser tab.
         *
         * waitForPopup() captures that new page.
         */
        return page.waitForPopup(() -> {

            Locator patientLink = page.getByRole(
                AriaRole.LINK,
                new Page.GetByRoleOptions()
                    .setName(patientId)
                    .setExact(true)
            );

            // Wait until Patient ID is visible
            patientLink.waitFor();

            System.out.println(
                "Patient ID link found"
            );

            // Normal click is intentional here because
            // we need Playwright to capture the popup.
            patientLink.click();
        });
    }
}